before_install:
  - sudo apt install llvm-10
  - sudo pip3 install llvmlite
  - cd /usr/bin
  - sudo ln -s llvm-config-10 llvm-config
language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sMaif
  password:
    secure: OZrVK+pXUrEPlJDtWLuU0I5C2qcdrQ3A7A6JL/pnobz4zWRoO/W2LB5TJX23Czfewwf7EgPwOgoHLdoUlqbfX0TykFtN6ao6qKZSmkdpL/Cbacl5d7hZ7267MW7wL5VJLzSjuaP5ovedNhRiVg0smunExE12AUy6B68rCUG7VRWYTaMyX980PCwWLsLadJ0XIIqIh1cgIX+vDn0wyq6aewCZRdHU4RuLGQYfejNrx7I17WEM9fOCJIxKePGkRn0pXbdkY/0RNwwdJ+Vltq5IIF7KCv2yYWgfGlyV+OBUG1zDIE4Xhc4L+ECV/3Ipu6uoFsDZALXotjhcUtD+kSD/XcR9Zkym87oebP/ItU0RW0O2cSmuFCKF1/Z51MuRQ+8dF386UQy2cLqxcR4U9VZtuIUZBZLW73Y0YUVD20Ki2CcgplXlM7bsYLIEsQr8cZjA2RVXP4Zkgx5HJPUPTgiSwP8sgZ68/JMJIFkJGO8Wj9OtdroR0ZLlMeM51J6ACa7cxrKO5jbbCfQJ31GtR7ZajD12mkfSwhea81JwlPWPhWx94bmyhJ0FcwmFSi8GHk7r26eC5M/+K4x6/ywXq6dAJhCmJMGMj64enQgOU5gmPx6vfLw5a+z/10xNmfDdKDSiMFPSyB2xplLV/a11Mwbpo8gPOCs86wy7x/99wxOUHFI=
  on:
    tags: true
    repo: MAIF/shapash
    python: 3.6
